[2025-03-08T00:05:31.384+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-08T00:05:31.388+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_payments.etl_process scheduled__2025-03-07T00:00:00+00:00 [queued]>
[2025-03-08T00:05:31.392+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_payments.etl_process scheduled__2025-03-07T00:00:00+00:00 [queued]>
[2025-03-08T00:05:31.392+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-08T00:05:31.400+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): etl_process> on 2025-03-07 00:00:00+00:00
[2025-03-08T00:05:31.422+0000] {standard_task_runner.py:72} INFO - Started process 1045 to run task
[2025-03-08T00:05:31.435+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_payments', 'etl_process', 'scheduled__2025-03-07T00:00:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/etl-payments.py', '--cfg-path', '/tmp/tmp8e5trv5c']
[2025-03-08T00:05:31.440+0000] {standard_task_runner.py:105} INFO - Job 172: Subtask etl_process
[2025-03-08T00:05:31.525+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_payments.etl_process scheduled__2025-03-07T00:00:00+00:00 [running]> on host 0de34880e4f2
[2025-03-08T00:05:31.597+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_payments' AIRFLOW_CTX_TASK_ID='etl_process' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-07T00:00:00+00:00'
[2025-03-08T00:05:31.599+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-08T00:05:31.623+0000] {etl-payments.py:31} INFO - üîπ Mengambil data dari database sumber...
[2025-03-08T00:05:43.022+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/etl-payments.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-03-08T00:05:48.651+0000] {etl-payments.py:36} INFO - ‚úÖ Data berhasil diambil!
[2025-03-08T00:05:48.654+0000] {etl-payments.py:38} INFO - üîπ Memproses data...
[2025-03-08T00:05:48.792+0000] {etl-payments.py:59} INFO - ‚úÖ Data berhasil dibersihkan!
[2025-03-08T00:05:49.922+0000] {etl-payments.py:71} INFO - üîç Data baru yang ditemukan: 16 record(s)
[2025-03-08T00:05:50.179+0000] {etl-payments.py:82} INFO - ‚úÖ 16 data baru berhasil dimasukkan ke database!
[2025-03-08T00:05:50.182+0000] {etl-payments.py:88} INFO - ‚úÖ Proses ETL selesai!
[2025-03-08T00:05:50.237+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-08T00:05:50.259+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-08T00:05:50.259+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_payments, task_id=etl_process, run_id=scheduled__2025-03-07T00:00:00+00:00, execution_date=20250307T000000, start_date=20250308T000531, end_date=20250308T000550
[2025-03-08T00:05:50.311+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-08T00:05:50.338+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-08T00:05:50.339+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
