[2025-03-07T06:46:34.496+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-07T06:46:34.500+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_payments.etl_process manual__2025-03-07T06:46:31.524897+00:00 [queued]>
[2025-03-07T06:46:34.502+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_payments.etl_process manual__2025-03-07T06:46:31.524897+00:00 [queued]>
[2025-03-07T06:46:34.503+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-07T06:46:34.508+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): etl_process> on 2025-03-07 06:46:31.524897+00:00
[2025-03-07T06:46:34.513+0000] {standard_task_runner.py:72} INFO - Started process 120 to run task
[2025-03-07T06:46:34.518+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_payments', 'etl_process', 'manual__2025-03-07T06:46:31.524897+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/etl-payments.py', '--cfg-path', '/tmp/tmp1del6ms_']
[2025-03-07T06:46:34.519+0000] {standard_task_runner.py:105} INFO - Job 160: Subtask etl_process
[2025-03-07T06:46:34.544+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_payments.etl_process manual__2025-03-07T06:46:31.524897+00:00 [running]> on host 98bc23959960
[2025-03-07T06:46:34.578+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_payments' AIRFLOW_CTX_TASK_ID='etl_process' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T06:46:31.524897+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-07T06:46:31.524897+00:00'
[2025-03-07T06:46:34.579+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-07T06:46:34.586+0000] {etl-payments.py:31} INFO - ðŸ”¹ Mengambil data dari database sumber...
[2025-03-07T06:46:46.088+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/etl-payments.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-03-07T06:46:52.096+0000] {etl-payments.py:36} INFO - âœ… Data berhasil diambil!
[2025-03-07T06:46:52.099+0000] {etl-payments.py:38} INFO - ðŸ”¹ Memproses data...
[2025-03-07T06:46:52.172+0000] {etl-payments.py:59} INFO - âœ… Data berhasil dibersihkan!
[2025-03-07T06:47:24.760+0000] {etl-payments.py:99} INFO - âœ… Data baru berhasil dimasukkan ke database!
[2025-03-07T06:47:24.862+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-07T06:47:24.884+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-07T06:47:24.885+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_payments, task_id=etl_process, run_id=manual__2025-03-07T06:46:31.524897+00:00, execution_date=20250307T064631, start_date=20250307T064634, end_date=20250307T064724
[2025-03-07T06:47:24.946+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-07T06:47:24.978+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-07T06:47:24.979+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
