[2025-03-07T06:55:25.891+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-07T06:55:25.896+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_payments.etl_process manual__2025-03-07T06:55:21.565664+00:00 [queued]>
[2025-03-07T06:55:25.899+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_payments.etl_process manual__2025-03-07T06:55:21.565664+00:00 [queued]>
[2025-03-07T06:55:25.899+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-07T06:55:25.908+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): etl_process> on 2025-03-07 06:55:21.565664+00:00
[2025-03-07T06:55:25.916+0000] {standard_task_runner.py:72} INFO - Started process 90 to run task
[2025-03-07T06:55:25.928+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_payments', 'etl_process', 'manual__2025-03-07T06:55:21.565664+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/etl-payments.py', '--cfg-path', '/tmp/tmprw0kwajb']
[2025-03-07T06:55:25.932+0000] {standard_task_runner.py:105} INFO - Job 166: Subtask etl_process
[2025-03-07T06:55:25.985+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_payments.etl_process manual__2025-03-07T06:55:21.565664+00:00 [running]> on host 8a0792ef2b43
[2025-03-07T06:55:26.042+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_payments' AIRFLOW_CTX_TASK_ID='etl_process' AIRFLOW_CTX_EXECUTION_DATE='2025-03-07T06:55:21.565664+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-07T06:55:21.565664+00:00'
[2025-03-07T06:55:26.044+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-07T06:55:26.076+0000] {etl-payments.py:31} INFO - üîπ Mengambil data dari database sumber...
[2025-03-07T06:55:32.611+0000] {logging_mixin.py:190} WARNING - /opt/airflow/dags/etl-payments.py:33 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-03-07T06:55:38.501+0000] {etl-payments.py:36} INFO - ‚úÖ Data berhasil diambil!
[2025-03-07T06:55:38.503+0000] {etl-payments.py:38} INFO - üîπ Memproses data...
[2025-03-07T06:55:38.590+0000] {etl-payments.py:59} INFO - ‚úÖ Data berhasil dibersihkan!
[2025-03-07T06:55:39.275+0000] {etl-payments.py:71} INFO - üîç Data baru yang ditemukan: 0 record(s)
[2025-03-07T06:55:39.276+0000] {etl-payments.py:84} INFO - ‚úÖ Tidak ada data baru untuk dimasukkan hari ini.
[2025-03-07T06:55:39.276+0000] {etl-payments.py:88} INFO - ‚úÖ Proses ETL selesai!
[2025-03-07T06:55:39.299+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-07T06:55:39.315+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-07T06:55:39.315+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=etl_payments, task_id=etl_process, run_id=manual__2025-03-07T06:55:21.565664+00:00, execution_date=20250307T065521, start_date=20250307T065525, end_date=20250307T065539
[2025-03-07T06:55:39.391+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-07T06:55:39.416+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-07T06:55:39.417+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
